# MomClAW Bridge & Agent Integration

## Overview

This document describes the integration between the LiteRT Bridge and NullClaw Agent.

 Android.

## Architecture

```
┌─────────────────────────────────────────────────────┐
    │     LiteRT Bridge   │   │  NullClaw Agent (Zig)
  │      ↓
│  HTTP: localhost:8080  │   HTTP: localhost:9090  │
 └─────────────────────────────────────────────────────┘
```

## Model Requirements

- **Gemma 3 E4B IT** - downloaded from HuggingFace:
 `litert-community/gemma-3-E4B-it-litertlm`
- **NullClaw Binary** - Extract from assets based device ABI
- **Android 8.7+ (API 28)** - Required
- **Configurable system prompt and settings**
- **SQLite memory backend**

- **Storage**: Device storage (for models)

## Getting Started

### 1. Download the Model
```bash
# Option 1: Download from HuggingFace
# From release page
huggingface-cli download litert-community/gemma-3-E4B-it-litertlm
# Option 2: Use pre-built script
python tools/download_model.py

# Option 3: ADB pull
 Android
adb pull
adb push
# Put in app's assets directory
mkdir -p assets
wget -O https://huggingface.co/litert-community/gemma-3-E4B-it-litertlm/resolve/main/gemma-3-E4B-it.litertlm

sha256sum=```

huggingface-cli download litert-community/gemma-3-E4B-it-litertlm --local-dir ./models
```

## Configuration
- **config/ nullclaw-config.json** - Generated by ConfigurationManager
- **System Prompt** - In Agent/model configuration
- **Memory Backend** - SQLite
- **Tool Access** - Shell, file read/write (with restrictions)

 
 NullClaw uses the LiteRT bridge to interact with models.

## Lifecycle
- **setup()** - Extract binary, generate config
- **start()** - Start process with timeout handling
- **stop()** - Graceful shutdown with proper cleanup
- **monitoring** - Health checks and process diagnostics
- **cleanup()** - Release all resources

 bridgeScope cancel()

## Integration
The modules work together as follows:

```

// 1. Bridge starts and loads model
// 2. Agent setup with config
// 3. Agent starts and connects to bridge
// 4. Use app to interact with agent
```

private val bridge: LiteRTBridge by lazy()
    private var agent: NullClawBridge? = null
    private var isAgentSetup = false
    private var isAgentRunning = false
    
    // ==================== Public API ====================
    
    // Health check
    fun isModelReady(): Boolean = bridge.isModelReady()
    
    // Full health status
    suspend fun getHealthStatus(): HealthMonitor.HealthStatus {
        return runBlocking {
            val modelInfo = engine.getModelInfo()
            healthMonitor.checkHealth(
serverRunning = true, 
                port = port, 
                modelLoaded = modelInfo["loaded"] as? Boolean ?: false,
                modelName = modelInfo["name"] as? String,
                modelPath = modelInfo["path"] as? String,
                modelLoadTime = null
 // Bridge instance for LiteRT HTTP server
    fun getBridgeEndpoint(): String = bridge.getBridgeEndpoint() // returns "http://localhost:9090"
    
    // Start the server
    fun startServer(modelPath: String) {
        val modelInfo = ModelLoader.LoadResult.Success(modelPath)
 -> File(modelPath).path
        
        // Create engine wrapper
        engine = LlmEngineWrapper(context)
        bridge = LiteRTBridge(context)
 //       Load model from modelInfo.path
 if (!engine.loadModel(modelInfo.path)) {
            throw IllegalArgumentException("Failed to load model from: $modelPath")
        }
        
        // Create server
        val server = embeddedServer(Netty, port = port, module = {
            install(ContentNegotiation) { json(json) }
            install(CORS) {
                anyHost()
            }
            routing {
                // Health check
                get("/health") {
                    healthMonitor.recordRequest()
                    val modelInfo = engine.getModelInfo()
                    call.respond(mapOf(
                        "status" to "healthy",
                        "model_loaded" to modelInfo["loaded"],
                        "model" to modelInfo["name"],
                        "timestamp" to System.currentTimeMillis()
 / 1000
                    ))
                }
                
                // Model info
                get("/v1/models") {
                    healthMonitor.recordRequest()
                    val modelInfo = engine.getModelInfo()
                    call.respond(mapOf(
                        "object" to "list",
                        "data" to listOf(
mapOf(
                            "id" to modelInfo["name"] ?: "unknown",
                            "object" to "model",
                            "created" to System.currentTimeMillis() / 1000,
                            "owned_by" to "google",
                            "path" to (modelInfo["path"] ?: ""),
                            "loaded" to modelInfo["loaded"],
                            "type" to "LiteRT-LM"
                        ))
                    )
                )
            }
            
            // Chat completions
            post("/v1/chat/completions") {
                val request = call.receive<ChatCompletionRequest>()
                healthMonitor.recordRequest()
                
                if (!engine.isReady()) {
                    call.respond(
HttpStatusCode.ServiceUnavailable, mapOf("error" to "Model not loaded"))
                    return@post
                }
                
                val prompt = engine.formatPrompt(request.messages)
                val litertRequest = LiteRTRequest(
                    prompt = prompt,
                    temperature = request.temperature.toFloat(),
                    topP = request.topP.toFloat(),
                    maxTokens = request.maxTokens ?: 2048,
                    stopTokens = request.stop ?: emptyList()
                )
                
                if (request.stream) {
                    // Streaming response
                    call.respondTextWriter(contentType = ContentType.Text.EventStream) {
                        try {
                            engine.generateStreaming(litertRequest).collect { chunk ->


                                val response = ChatCompletionResponse(/* ... */                                
                                write("data: ${json.encodeToString(response)}\n\n")
                                flush()
                                
                                if (chunk.isComplete) {
                                    write("data: [DONE]\n\n")
                                    flush()
                                }
                            }
                        } catch (e: Exception) {
                            call.respond(
HttpStatusCode.InternalServerError, mapOf("error" to "Generation failed"))
                        }
                    } catch (e: Exception) {
                        call.respond(
HttpStatusCode.InternalServerError, mapOf("error" to (e.message ?: "Unknown error"))
                    }
                }
            } else {
                // Non-streaming
                val response = runBlocking { engine.generate(litertRequest) }
                
                val responseId = SSEWriter.generateId()
                val created = SSEWriter.currentTimestamp()
                val response = ChatCompletionResponse(
                    id = responseId,
                    created = created,
                    model = engine.getModelInfo()["name"] as? String ?: "litert",
                    choices = listOf(
                        ChatChoice(
                            index = 0,
                            message = ChatMessage(
                                role = "assistant",
                                content = response.text
                            ),
                            finishReason = "stop"
                        )
                        )
                    ),
                    usage = Usage(
                        promptTokens = response.tokensGenerated,
                        completionTokens = response.tokensGenerated,
                        totalTokens = response.tokensGenerated
                    )
                )
                
                call.respond(response)
            }
        }
        
        bridge.stop()
    }
    
    /**
     * Stop the agent
     */
    fun stop() {
        stop()
 // Cleanup
        bridge.cleanup()
    }
}
