package com.loa.momclaw.ui.theme

import androidx.compose.ui.graphics.Color

// Primary colors (Dark theme default)
val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

// MOMCLAW brand colors
val ClawPrimary = Color(0xFF1A73E8)
val ClawPrimaryDark = Color(0xFF0D47A1)
val ClawSecondary = Color(0xFF03DAC6)
val ClawSecondaryDark = Color(0xFF018786)
val ClawBackground = Color(0xFF121212)
val ClawSurface = Color(0xFF1E1E1E)
val ClawOnBackground = Color(0xFFE1E1E1)
val ClawOnSurface = Color(0xFFE1E1E1)

// Chat colors
val UserMessageBackground = Color(0xFF2D5F8B)
val AssistantMessageBackground = Color(0xFF2A2A2A)

// Light Theme
val md_theme_light_primary = Color(0xFF1A73E8)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD3E3FD)
val md_theme_light_onPrimaryContainer = Color(0xFF041E49)
val md_theme_light_secondary = Color(0xFF03DAC6)
val md_theme_light_onSecondary = Color(0xFF003731)
val md_theme_light_secondaryContainer = Color(0xFF9EF1E5)
val md_theme_light_onSecondaryContainer = Color(0xFF00201C)
val md_theme_light_tertiary = Color(0xFF5F5C71)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE5DEF9)
val md_theme_light_onTertiaryContainer = Color(0xFF1C192B)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFFEF7FF)
val md_theme_light_onBackground = Color(0xFF1D1B20)
val md_theme_light_surface = Color(0xFFFEF7FF)
val md_theme_light_onSurface = Color(0xFF1D1B20)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454E)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_outlineVariant = Color(0xFFCAC4D0)
val md_theme_light_inverseSurface = Color(0xFF322F35)
val md_theme_light_inverseOnSurface = Color(0xFFF5EFF7)
val md_theme_light_inversePrimary = Color(0xFFABC7FF)
val md_theme_light_surfaceTint = Color(0xFF1A73E8)
val md_theme_light_scrim = Color(0xFF000000)

// Dark Theme
val md_theme_dark_primary = Color(0xFFABC7FF)
val md_theme_dark_onPrimary = Color(0xFF0E2E60)
val md_theme_dark_primaryContainer = Color(0xFF0842A0)
val md_theme_dark_onPrimaryContainer = Color(0xFFD3E3FD)
val md_theme_dark_secondary = Color(0xFF80DED6)
val md_theme_dark_onSecondary = Color(0xFF003731)
val md_theme_dark_secondaryContainer = Color(0xFF004F47)
val md_theme_dark_onSecondaryContainer = Color(0xFF9EF1E5)
val md_theme_dark_tertiary = Color(0xFFC9C0DC)
val md_theme_dark_onTertiary = Color(0xFF322E41)
val md_theme_dark_tertiaryContainer = Color(0xFF484558)
val md_theme_dark_onTertiaryContainer = Color(0xFFE5DEF9)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF121212)
val md_theme_dark_onBackground = Color(0xFFE6E1E6)
val md_theme_dark_surface = Color(0xFF1E1E1E)
val md_theme_dark_onSurface = Color(0xFFE6E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF49454E)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_outlineVariant = Color(0xFF49454E)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E6)
val md_theme_dark_inverseOnSurface = Color(0xFF322F35)
val md_theme_dark_inversePrimary = Color(0xFF1A73E8)
val md_theme_dark_surfaceTint = Color(0xFFABC7FF)
val md_theme_dark_scrim = Color(0xFF000000)
